### PR TITLE
Lucida compilation fix on recent Ubuntu 14.04.5, generic backend and mini setup repository

### PR DESCRIPTION
**Pull request by k0105**
Hi,
with minimal changes Lucida can be made to compile on Ubuntu 14.04.5. I have a more involved attempt to get it to compile under 16.04 here https://github.com/k0105/lucida_experimental that you might want to take a look at as well, but while this solves a few errors it still does not fully compile under 16.04 due to problems with the image matching service.

Regarding the generic backend and the mini repository to run Lucida on both 14.04 and 16.04 with minimal effort which are more substantial controibutions please just fork their repositories:
https://github.com/k0105/lucidagenericbackend
https://github.com/k0105/mini-lucida

Best wishes,
k0105

### CODE REVIEW

**Comment by k0105** [comment]
I have added the generic backend as a subdirectory to the lucida directory.
Thus, you can just accept the pull request to fix compilation and add the generic backend, but it still makes sense to fork https://github.com/k0105/mini-lucida since this is only intended for users who only want to run Lucida without cloning 6000x more data than they need - putting it inside the main repo would defeats its purpose or at least make it more obscure to use.

**Comment by k0105** [comment]
I also added the additions from mini-lucida to the tools/deploy subdirectory. I still recommend to fork https://github.com/k0105/mini-lucida - sparse checkouts are possible, but they add unnecessary complexity to the process, esp. for users who just want to run Lucida, possibly not even modify it.

**Comment by k0105** [comment]
Just added a generic backend in Python as well, also asynchronous.

**Comment by jhauswald** [comment]
Thanks for the PR, looks like quite the stack of changes! What I'd like to do is break this up into different PRs to make the code review more effective and manageable from my side. Here's what I have in mind for each PR:
- compilation fixes
- the generic backend

I'm thinking the mini setup repo should be a separate repo and not be a PR to this repo. Also moving forward to make the development more streamlined on your side and Sapphire, and on my side we should have a single codebase, sounds like you're suggesting forking your repos in the PR comments. Also can you elaborate on the extra licenses you're suggesting the PR? Let me know what you think,

**Comment by k0105** [comment]
The mini-lucida part here is only an addition to Yunsheng's Kubernetes scripts, since he has no script that installs all dependencies like Docker and Docker Compose - for the standalone part I agree, you can just fork the mini-lucida repository. Besides that there is nothing to fork - the backends are already integrated into your monolithic repository.

The generic backends are under Apache license (ASLv2), since all my code is Apache licensed just like YodaQA and its backend, which makes it quite homogeneous to work with (one license for 13 services). [I still need to add a note to the Python backend.]

Regarding multiple pull requests - I tried that, but my pull requests were merged into this thread. Not sure if I did something wrong or whether Github just wants you to go by commits (which is easily possible - besides the files I removed it's fix, install script, backend1, backend 2).

I'll look over this again soon, but for now I should get the Server fixes tested and pushed for Li tomorrow.

**Comment by k0105** [comment]
Update: Lucida should now work on Ubuntu 14.04 Server as well, cmp. https://github.com/k0105/lucidaserverexperiment/ I'll extend the PR soon.

**Pull request closed without merging**
