### PR TITLE
[WIP] Dockerfile for Sirius base image

### PR DESCRIPTION
**Pull request by viklas**
##### This Docker image is still WIP - not all sirius server components have been tested successfully. Q&A server has passed testing.

This PR includes a Dockerfile to prepare a 'base' sirius server image (Ubuntu 12.04 + all apt-get package dependencies). 

Also included is /sirius-application/start.sh which is a basic script to call get-opencv.sh, get-kaldi.sh and compile-sirius-servers.sh (TODO: include run/test scripts).

Lastly, some README notes have been included to explain how the docker deployment works.

#####Links to open issues:
ISSUE UPDATE: #22 - openfst working in docker image
ISSUE UPDATE: #23 - ffmpeg working in docker image
ISSUE UPDATE: #25 - openfst working in docker image
ISSUE RECOMMEND CLOSE: #26 - Base docker image (v0.1) WIP but working for Q&A server
ISSUE UPDATE: #30 - Sox included in docker image
ISSUE UPDATE: #36 - all operations in docker image will run as sudo currently
ISSUE UPDATE: #46 - opencv sources working in docker image
ISSUE UPDATE: #49 - protobuff 2.5.0 working in docker image

### CODE REVIEW

**Comment by jhauswald** [comment]
We've been following the docker push closely and this is how it looks from our side:



I've personally never worked with docker so its a good opportunity for me to learn about it before merging  it in so I appreciate the patience!

**Comment by viklas** [comment]
That dog needs to take some life lessons from this Redditor:
http://www.reddit.com/r/tifu/comments/306xj9/tifu_by_not_wearing_any_clothes/

Must admit, sirius proved to be about 10x harder to nail down into a basic dockerfile than we first thought, but will be worth it (should get some good distributed development going). There's still some techniques to streamline, and most important to that would be trimming down the sirius repo to a much smaller footprint (store any big files externally on s3 or something)...but this approach works for now to get things moving.

**Comment by kolewu** [comment]
How did you get a running Q&A without the wiki index?  I'm just waiting for #42  to not have to download 13 GB, unpack 13 GB from the archive and then extract the wiki-index from this.  This is working but clumsy:

```
# cd $GITROOT
curl -O http://web.eecs.umich.edu/~jahausw/download/sirius-1.0.tar.gz
mkdir tmp
tar -xf sirius-1.0.tar.gz -C tmp sirius-application-1.0.tar.gz
tar -xf tmp/sirius-application-1.0.tar.gz sirius-application/wiki_indri_index.tar.gz
cd sirius-application
tar xvf wiki_indri_index.tar.gz -C question-answer/
rm tmp/sirius-application-1.0.tar.gz sirius-application/wiki_indri_index.tar.gz
```

**Comment by viklas** [comment]
As a general rule, for this v0.1 solution, the instructions on the siris website for starting each server still need to be followed (agree it is slooow). I think when we eventually create a simpler 'runtime' container that is minified, and includes the compiled binaries, we can probably start including some of those prep steps. Our current method is the same as yours and not Production ready...but there's a handy aspect of having the attached docker volume, in that you can modify the contents of the volume from the docker host. I'd recommend saving that extracted wiki file somewhere handy, and just copying it into the cloned repo directory on the host when doing a deployment, for the time being (saves the download/tar, etc for something which is basically static content).

**Comment by Estevo-Aleixo** [comment]
mkdir sirius-application
    mkdir sirius-application/question-answer/
    curl http://web.eecs.umich.edu/~jahausw/download/sirius-1.0.tar.gz | tar -xzO sirius-application-1.0.tar.gz | tar -xzO sirius-application/wiki_indri_index.tar.gz | tar -xzvC sirius-application/question-answer/

**Comment by viklas** [comment]
Someone asked for some more detailed instructions on how to go end-to-end with the docker process - here's a gist with the steps. I tested it on digitalocean, but will work on any host running docker.

https://gist.github.com/viklas/639d2f49a8ff2819fde4

Whilst the current PR is marked [WIP], this is actually ready to be merged as far as I can tell. Not sure if there's a reason for not merging, but we've been able to use it successfully.

**Comment by Anaeijon** [comment]
Dear Luke Benson,

The email sent to david@d-doering.tk with subject
"Re: [sirius] [WIP] Dockerfile for Sirius base image (#55)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Pull request closed without merging**
